version: '3.5'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: "my-elasticsearch"
    env_file:
     - docker.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: "my-kibana"
    image: docker.elastic.co/kibana/kibana:7.12.0
    env_file:
     - docker.env
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  #Postgres
  postgres:
    container_name: "my-postgres_container"
    image: postgres
    env_file:
     - docker.env
    volumes:
      - db_post:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - aminnet
    restart: unless-stopped
  
  pgadmin:
    container_name: "my-pgadmin_container"
    image: dpage/pgadmin4
    env_file:
      - docker.env
    volumes:
      - db_pgadmin:/root/.pgadmin:rw
    ports:
      - "5050:80"
    networks:
      - aminnet
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: "my-mysqldev"
    volumes:
      - db_mysql:/var/lib/mysql:rw
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - aminnet
    env_file:
      - docker.env

  mongodev:
    container_name: "my-mongodev"
    image: mongo
    ports:
      - "27017:27017"
    networks:
        - aminnet
    expose:
      - 27017
    restart: always
    volumes:
      - db_mongo:/data/db:rw

  #Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: "my-redis"
    volumes:
        - db_redis:/data:rw
    networks:
        - aminnet
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 90:8080
    expose:
      - 90
    networks:
        - aminnet
  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '60:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: amin@Mysql
    networks:
      - aminnet
networks:
  aminnet:
    external: true

volumes:
  elasticsearch-data:
    driver: local
  db_mysql: {}
  db_mongo: {}
  db_post: {}
  db_redis: {}
  db_pgadmin: {}