version: '3.5'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: "my-elasticsearch"
    env_file:
      - docker.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

networks:
  aminnet:
    external: true

volumes:
  elasticsearch-data:
    driver: local
  db_mysql: {}
  db_mongo: {}
  db_post: {}
  db_redis: {}
  db_pgadmin: {}