version: '3.5'

services:

  db:
    image: mysql:8.0
    container_name: "my-mysqldev"
    volumes:
      - db_mysql:/var/lib/mysql:rw
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - aminnet
    env_file:
      - docker.env

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '60:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: amin@Mysql
      UPLOAD_LIMIT: 300M
    networks:
      - aminnet
networks:
  aminnet:
    external: true

volumes:
  elasticsearch-data:
    driver: local
  db_mysql: {}