version: '3.5'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: "my-redis"
    volumes:
        - db_redis:/data:rw
    networks:
        - aminnet

networks:
  aminnet:
    external: true

volumes:
  db_redis: {}